services:
  mongo:
    image: mongo:7
    container_name: stylehub_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: stylehub_backend
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/stylehub
      JWT_SECRET: stylehub_secret_key
      CLIENT_URL: http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: stylehub_frontend
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  mongo_data:
